version: '3.8'

services:
  crypto_pg:
    image: postgres:16-alpine
    container_name: crypto_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: crypto_db
    volumes:
      - db_storage:/var/lib/postgresql/data
volumes:
  db_storage: